const x = 5;

try{
    x + 2;
    console.log("Otrye deu certo!")
} catch(error){
    console.log(error)
}